---
title: "元器件生存时间模拟分析-增加两个参数"
author: "Miao Cai"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    number_sections: true
bibliography: ref.bib
csl: chinese.csl
link-citations: true
linkcolor: blue
header-includes:
  - \usepackage{soulutf8}
  - \usepackage{color}
  - \usepackage{float}
  - \usepackage[UTF8]{ctex}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# A2

```{r eval=FALSE}
set.seed(123)

alpha = matrix(c(0.005, 0.05, 0.0005, 0.08), ncol = 2, byrow = TRUE)
w = c(45, 55)
t = matrix(seq(10, 40, 10), ncol = 2, byrow = TRUE)
K = c(10, 50, 100)


lambda = function(r = 1:2, j = 1:2) {
  alpha_r0 = alpha[r, 1]
  alpha_r1 = alpha[r, 2]
  return(alpha_r0*exp(alpha_r1*w[j]))
}

p = function(i = 1:2, j = 1:2){
  lam1j = lambda(1, j) # failure due to factor 1
  lam2j = lambda(2, j) # failure due to factor 2
  
  p0 = exp(-(lam1j + lam2j)*t[i, j])
  p1 = (lam1j/(lam1j + lam2j))*(1 - p0)
  p2 = (lam2j/(lam1j + lam2j))*(1 - p0)
  
  return(c(p0, p1, p2))
}

Tmatrxi = t(rmultinom(100, K[3], prob = p(1, 1)))
```



```{r eval=FALSE}
reliab = "
data {
  int<lower=0> n;
  int DAT[n, 3];
  vector[2] W;
  vector[4] Tim;
}
parameters{
  real<lower=0, upper=0.5> a10; 
  real<lower=0, upper=0.5> a11;
  real<lower=0, upper=0.5> a20; 
  real<lower=0, upper=0.5> a21;
}
transformed parameters{
  real<lower=0, upper=1> p0; 
  real<lower=0, upper=1> p1; 
  real<lower=0, upper=1> p2;
  vector<lower=0, upper=1>[3] p;
  
  p0 = exp(-(a10*exp(a11*W[1]) + a20*exp(a21*W[2]))*Tim[1]);
  p1 = (a10*exp(a11*W[1]))/(a10*exp(a11*W[1]) + a20*exp(a21*W[2]))*(1 - p0);
  p2 = 1-p0-p1;
  p = [p0, p1, p2]';
}
model{
  for (i in 1:n){
    //target += multinomial_lpmf(DAT[i,] | p);
    DAT[i,] ~ multinomial(p);
    //DAT[i,] ~ multi_log(p0, p1, p2);
  }
  a10 ~ gamma(1, 10);
  a11 ~ gamma(1, 10);
  a20 ~ gamma(1, 10);
  a21 ~ gamma(1, 10);
}
"

library(rstan)
rstan_options(auto_write = TRUE)

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 1, cores = 1, seed = 3)

summary(fit)
round(summary(fit)$summary[,1], 4)
```


```{r eval=FALSE}
# N = 10
set.seed(123)
Tmatrxi = t(rmultinom(10, 10, prob = p(1, 1)))

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit10 <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 3, cores = 3, seed = 3, 
  control = list(adapt_delta = 0.95, max_treedepth = 15))

# N = 50
set.seed(123)
Tmatrxi = t(rmultinom(50, 50, prob = p(1, 1)))

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit50 <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 3, cores = 3, seed = 3, 
  control = list(adapt_delta = 0.95, max_treedepth = 15))


# N = 100
set.seed(123)
Tmatrxi = t(rmultinom(100, 100, prob = p(1, 1)))

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit100 <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 3, cores = 3, seed = 3, 
  control = list(adapt_delta = 0.95, max_treedepth = 15))


# N = 500
set.seed(123)
Tmatrxi = t(rmultinom(500, 500, prob = p(1, 1)))

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit500 <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 3, cores = 3, seed = 3, 
  control = list(adapt_delta = 0.95, max_treedepth = 15))



# N = 1000
set.seed(123)
Tmatrxi = t(rmultinom(1000, 1000, prob = p(1, 1)))

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit1000 <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 3, cores = 3, seed = 3, 
  control = list(adapt_delta = 0.95, max_treedepth = 15))

# write out tables
wtab = function(fit, filename){
  dat = as.data.frame(summary(fit)$summary[1:7,])
  write.csv(dat, paste0('data/A2/', filename))
}

wtab(fit10, 'fit10.csv')
wtab(fit50, 'fit50.csv')
wtab(fit100, 'fit100.csv')
wtab(fit500, 'fit500.csv')
wtab(fit1000, 'fit1000.csv')

saveRDS(fit10, 'data/A2/fit10.rds')
saveRDS(fit50, 'data/A2/fit50.rds')
saveRDS(fit100, 'data/A2/fit100.rds')
saveRDS(fit500, 'data/A2/fit500.rds')
saveRDS(fit1000, 'data/A2/fit1000.rds')

plot(fit10, plotfun = "trace", #inc_warmup = TRUE,
     pars = c("a10", "a11", "a20", "a21", "p0", "p1", "p2"))
ggsave('data/A2/fit10.png', dpi = 300, height = 6.18, width = 10)
plot(fit50, plotfun = "trace", #inc_warmup = TRUE,
     pars = c("a10", "a11", "a20", "a21", "p0", "p1", "p2"))
ggsave('data/A2/fit50.png', dpi = 300, height = 6.18, width = 10)
plot(fit100, plotfun = "trace", #inc_warmup = TRUE,
     pars = c("a10", "a11", "a20", "a21", "p0", "p1", "p2"))
ggsave('data/A2/fit100.png', dpi = 300, height = 6.18, width = 10)
plot(fit500, plotfun = "trace", #inc_warmup = TRUE,
     pars = c("a10", "a11", "a20", "a21", "p0", "p1", "p2"))
ggsave('data/A2/fit500.png', dpi = 300, height = 6.18, width = 10)
plot(fit1000, plotfun = "trace", #inc_warmup = TRUE,
     pars = c("a10", "a11", "a20", "a21", "p0", "p1", "p2"))
ggsave('data/A2/fit1000.png', dpi = 300, height = 6.18, width = 10)
```


# A3


```{r eval=FALSE}
set.seed(123)

alpha = matrix(c(0.008, 0.05, 0.0008, 0.08), ncol = 2, byrow = TRUE)
w = c(45, 55)
t = matrix(seq(10, 40, 10), ncol = 2, byrow = TRUE)
K = c(10, 50, 100)


lambda = function(r = 1:2, j = 1:2) {
  alpha_r0 = alpha[r, 1]
  alpha_r1 = alpha[r, 2]
  return(alpha_r0*exp(alpha_r1*w[j]))
}

p = function(i = 1:2, j = 1:2){
  lam1j = lambda(1, j) # failure due to factor 1
  lam2j = lambda(2, j) # failure due to factor 2
  
  p0 = exp(-(lam1j + lam2j)*t[i, j])
  p1 = (lam1j/(lam1j + lam2j))*(1 - p0)
  p2 = (lam2j/(lam1j + lam2j))*(1 - p0)
  
  return(c(p0, p1, p2))
}

Tmatrxi = t(rmultinom(100, K[3], prob = p(1, 1)))
```



```{r eval=FALSE}
reliab = "
data {
  int<lower=0> n;
  int DAT[n, 3];
  vector[2] W;
  vector[4] Tim;
}
parameters{
  real<lower=0, upper=0.5> a10; 
  real<lower=0, upper=0.5> a11;
  real<lower=0, upper=0.5> a20; 
  real<lower=0, upper=0.5> a21;
}
transformed parameters{
  real<lower=0, upper=1> p0; 
  real<lower=0, upper=1> p1; 
  real<lower=0, upper=1> p2;
  vector<lower=0, upper=1>[3] p;
  
  p0 = exp(-(a10*exp(a11*W[1]) + a20*exp(a21*W[2]))*Tim[1]);
  p1 = (a10*exp(a11*W[1]))/(a10*exp(a11*W[1]) + a20*exp(a21*W[2]))*(1 - p0);
  p2 = 1-p0-p1;
  p = [p0, p1, p2]';
}
model{
  for (i in 1:n){
    //target += multinomial_lpmf(DAT[i,] | p);
    DAT[i,] ~ multinomial(p);
    //DAT[i,] ~ multi_log(p0, p1, p2);
  }
  a10 ~ gamma(1, 10);
  a11 ~ gamma(1, 10);
  a20 ~ gamma(1, 10);
  a21 ~ gamma(1, 10);
}
"

library(rstan)
rstan_options(auto_write = TRUE)

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 1, cores = 1, seed = 3)

summary(fit)
round(summary(fit)$summary[,1], 4)
```


```{r eval=FALSE}
# N = 10
set.seed(123)
Tmatrxi = t(rmultinom(10, 10, prob = p(1, 1)))

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit10 <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 3, cores = 3, seed = 3, 
  control = list(adapt_delta = 0.95, max_treedepth = 15))

# N = 50
set.seed(123)
Tmatrxi = t(rmultinom(50, 50, prob = p(1, 1)))

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit50 <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 3, cores = 3, seed = 3, 
  control = list(adapt_delta = 0.95, max_treedepth = 15))


# N = 100
set.seed(123)
Tmatrxi = t(rmultinom(100, 100, prob = p(1, 1)))

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit100 <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 3, cores = 3, seed = 3, 
  control = list(adapt_delta = 0.95, max_treedepth = 15))


# N = 500
set.seed(123)
Tmatrxi = t(rmultinom(500, 500, prob = p(1, 1)))

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit500 <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 3, cores = 3, seed = 3, 
  control = list(adapt_delta = 0.95, max_treedepth = 15))



# N = 1000
set.seed(123)
Tmatrxi = t(rmultinom(1000, 1000, prob = p(1, 1)))

stan_dat = list(
  n = nrow(Tmatrxi),
  DAT = Tmatrxi,
  W = w,
  Tim = seq(10, 40, 10)
)

fit1000 <- stan(
  model_code = reliab, data = stan_dat, #init_r = 0.1, init = 0.001, 
  warmup = 1000, iter = 2000, chains = 3, cores = 3, seed = 3, 
  control = list(adapt_delta = 0.95, max_treedepth = 15))

# write out tables
wtab = function(fit, filename){
  dat = as.data.frame(summary(fit)$summary[1:7,])
  write.csv(dat, paste0('data/A3/', filename))
}

wtab(fit10, 'fit10.csv')
wtab(fit50, 'fit50.csv')
wtab(fit100, 'fit100.csv')
wtab(fit500, 'fit500.csv')
wtab(fit1000, 'fit1000.csv')

saveRDS(fit10, 'data/A3/fit10.rds')
saveRDS(fit50, 'data/A3/fit50.rds')
saveRDS(fit100, 'data/A3/fit100.rds')
saveRDS(fit500, 'data/A3/fit500.rds')
saveRDS(fit1000, 'data/A3/fit1000.rds')

plot(fit10, plotfun = "trace", #inc_warmup = TRUE,
     pars = c("a10", "a11", "a20", "a21", "p0", "p1", "p2"))
ggsave('data/A3/fit10.png', dpi = 300, height = 6.18, width = 10)
plot(fit50, plotfun = "trace", #inc_warmup = TRUE,
     pars = c("a10", "a11", "a20", "a21", "p0", "p1", "p2"))
ggsave('data/A3/fit50.png', dpi = 300, height = 6.18, width = 10)
plot(fit100, plotfun = "trace", #inc_warmup = TRUE,
     pars = c("a10", "a11", "a20", "a21", "p0", "p1", "p2"))
ggsave('data/A3/fit100.png', dpi = 300, height = 6.18, width = 10)
plot(fit500, plotfun = "trace", #inc_warmup = TRUE,
     pars = c("a10", "a11", "a20", "a21", "p0", "p1", "p2"))
ggsave('data/A3/fit500.png', dpi = 300, height = 6.18, width = 10)
plot(fit1000, plotfun = "trace", #inc_warmup = TRUE,
     pars = c("a10", "a11", "a20", "a21", "p0", "p1", "p2"))
ggsave('data/A3/fit1000.png', dpi = 300, height = 6.18, width = 10)
```

